export const START_FETCHING_STUDENTS = "START_FETCHING_STUDENTS";

export const FETCH_ALL_STUDENTS = "FETCH_ALL_STUDENTS"
export const FETCH_A_STUDENT = "FETCH_A_STUDENT"




export const ADD_A_STUDENT = "ADD_A_STUDENT"
export const REMOVE_A_STUDENT = "REMOVE_A_STUDENT"

