export const START_FETCHING_STUDENTS = "START_FETCHING_STUDENTS";
export const UPDATE_STUDENTS_TO_STATE = "ADD_STUDENTS_TO_STATE";
export const UPDATE_STUDENT_TO_STATE = "UPDATE_STUDENT_TO_STATE";

export const FETCH_ALL_STUDENTS = "FETCH_ALL_STUDENTS";
export const FETCH_A_STUDENT = "FETCH_A_STUDENT";




export const ADD_A_STUDENT = "ADD_A_STUDENT";
export const CALL_API_TO_ADD_STUDENT = "CALL_API_TO_ADD_CAMPUS";
export const ON_ADD_SUCCESS = "ON_ADD_SUCCESS";


export const REMOVE_A_STUDENT = "REMOVE_A_STUDENT";
export const CALL_API_TO_REMOVE_STUDENT = "CALL_API_TO_REMOVE_STUDENT";



